#! /bin/sh
# Author: JuanJo Ciarlante <juanjosec@gmail.com>
# License: GPLv3

### BEGIN INIT INFO
# Provides:          spawn-fcgi
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts spawn-fcgi
# Description:       starts spawn-fcgi using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/spawn-fcgi
NAME=spawn-fcgi
DESC=spawn-fcgi

#-P $(BOGOMON_PIDFILE) -d $(PWD)/$(BOGOMON_VAR_RUN) -a 127.0.0.1 -p $(BOGOMON_PORT) -- $(PWD)/$(BOGOMON_PY)  $(PWD)/$(RRD_FILE) $(PWD)/$(PNG_FILE)

RRD_FILE=/var/lib/bogomon/local.rrd
BOGOMON_PORT=9000
DAEMON_OPTS="-n -d /var/run/bogomon -a 127.0.0.1 -p $BOGOMON_PORT -u bogomon -- /usr/lib/bogomon/web/bogomon.fcgi.py $RRD_FILE /var/lib/bogomon/local.png"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	test -f $RRD_FILE || \
		rrdtool create $RRD_FILE -s 10 DS:cpurate:COUNTER:6:U:U RRA:AVERAGE:0.5:1:360 RRA:AVERAGE:0.5:10:36

	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet -bm --pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid || \
		fuser -s -k -n tcp $BOGOMON_PORT 
	echo "$NAME."
	;;
  restart)
        $0 stop;$0 start
	;;
  status)
	status_of_proc -p /var/run/$NAME.pid "$DAEMON" spawn-fcgi && exit 0 || exit $?
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0
